# Generated by Django 4.1 on 2022-09-14 09:52

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smwapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='status', unique=True),
        ),
        migrations.CreateModel(
            name='replycomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=300)),
                ('initial_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smwapp.comments')),
            ],
        ),
    ]
