# Generated by Django 4.1 on 2022-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smwapp', '0006_alter_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(),
        ),
    ]
